name = "glitr_wisp"
version = "0.1.7"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Interface for wisp to use Glitr's typed routes"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Billuc", repo = "glitr" }
links = [{ title = "Website", href = "https://hexdocs.pm/glitr_wisp" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
glitr = ">= 0.1.5 and < 1.0.0"
# glitr = { path = "../glitr" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
